# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{resource_mapper}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Elliot"]
  s.date = %q{2010-10-18}
  s.description = %q{Creates a resource for a model in sinatra}
  s.email = %q{adam@adamelliot.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".autotest",
     ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/example_helper.rb",
     "examples/lib/sinatra/resource_example.rb",
     "examples/models.rb",
     "lib/resource_mapper.rb",
     "lib/resource_mapper/accessors.rb",
     "lib/resource_mapper/action_options.rb",
     "lib/resource_mapper/actions.rb",
     "lib/resource_mapper/class_methods.rb",
     "lib/resource_mapper/controller.rb",
     "lib/resource_mapper/failable_action_options.rb",
     "lib/resource_mapper/helpers/current_objects.rb",
     "lib/resource_mapper/helpers/internal.rb",
     "lib/resource_mapper/helpers/nested.rb",
     "lib/resource_mapper/response_collector.rb",
     "lib/sinatra/resource.rb",
     "resource_mapper.gemspec"
  ]
  s.homepage = %q{http://github.com/adamelliot/resource_mapper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A resource_controller derivate that brings similar functionality to Sinatra, but provides a simple way to create restful APIs}
  s.test_files = [
    "examples/example_helper.rb",
     "examples/lib/sinatra/resource_example.rb",
     "examples/models.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 1.0"])
      s.add_runtime_dependency(%q<plist>, [">= 3.1.0"])
      s.add_runtime_dependency(%q<builder>, [">= 3.1.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<mongo_mapper>, [">= 0.8.4"])
      s.add_development_dependency(%q<micronaut>, [">= 0.3.0"])
      s.add_development_dependency(%q<rack-test>, [">= 0.5.5"])
    else
      s.add_dependency(%q<sinatra>, [">= 1.0"])
      s.add_dependency(%q<plist>, [">= 3.1.0"])
      s.add_dependency(%q<builder>, [">= 3.1.0"])
      s.add_dependency(%q<activesupport>, [">= 3.0.0"])
      s.add_dependency(%q<mongo_mapper>, [">= 0.8.4"])
      s.add_dependency(%q<micronaut>, [">= 0.3.0"])
      s.add_dependency(%q<rack-test>, [">= 0.5.5"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 1.0"])
    s.add_dependency(%q<plist>, [">= 3.1.0"])
    s.add_dependency(%q<builder>, [">= 3.1.0"])
    s.add_dependency(%q<activesupport>, [">= 3.0.0"])
    s.add_dependency(%q<mongo_mapper>, [">= 0.8.4"])
    s.add_dependency(%q<micronaut>, [">= 0.3.0"])
    s.add_dependency(%q<rack-test>, [">= 0.5.5"])
  end
end

